### ISSUE TITLE
Need to setup a pipeline for pushing a recently merging timbot image to an external container registry

### ISSUE THREAD

**Issue by timflannagan** [Daniel-Pivonka/timbot#85] opened 2020-08-07 19:05 UTC
Because @Daniel-Pivonka refuses to automate this locally, we should just try and set up a pipeline that pushes a merged timbot image to somewhere like quay or docker so the container running timbot on the local machine can be periodically rotated with newer images.

**Comment by nathan-weinberg** [comment] 2020-08-13 16:51
Duplicate of #82 no?

**Closed as completed** 2020-08-13 20:05 UTC
